### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by phpluo** [knightli/qiniu-uploader#12]
[Enter steps to reproduce:]

1. 直接粘贴截图失败，是我七牛没有配置好吗
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [qiniu-uploader](https://github.com/knightli/qiniu-uploader) package 0.0.3

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///C:/Users/Administrator/AppData/Local/atom/app-1.20.0/resources/app/static/index.html:2

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.exports.parse (/packages/qiniu-uploader/node_modules/sync-request/lib/json-buffer/index.js:46:15)
    at doRequest (/packages/qiniu-uploader/node_modules/sync-request/index.js:33:23)
    at Object.exports.up_host (/packages/qiniu-uploader/node_modules/qiniu/qiniu/zone.js:34:15)
    at putReadable (/packages/qiniu-uploader/node_modules/qiniu/qiniu/io.js:55:8)
    at Object.put (/packages/qiniu-uploader/node_modules/qiniu/qiniu/io.js:75:10)
    at Uploader.module.exports.Uploader.upload (/packages/qiniu-uploader/lib/uploader.coffee:28:14)
    at uploadFn (/packages/markdown-assistant/lib/main.coffee:57:23)
    at /packages/markdown-assistant/lib/insert-image-view.coffee:63:9
```

### Commands

```
  4x -9:08.3.0 core:paste (input.hidden-input)
     -2:15.2.0 intentions:highlight (input.hidden-input)
     -2:14.8.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.5 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
autocomplete-paths 2.11.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.11.0 
emmet 2.4.3 
file-icons 2.1.11 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.4.0 
linter-ui-default 1.6.8 
markdown-assistant 0.2.0 
markdown-preview-plus 2.4.10 
markdown-writer 2.7.2 
pigments 0.40.2 
platformio-ide-terminal 2.6.0 
qiniu-uploader 0.0.3 
regex-railroad-diagram 0.19.3 
script 3.15.0 
simplified-chinese-menu 5.3.4 
sync-settings 0.8.3 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
tool-bar-markdown-writer 0.3.0 
tree-view-git-status 1.4.0 
```

**Comment by morethink** [comment]
我也是

**Comment by tychenjiajun** [comment]
应该是七牛的接口有变
原作者好像不上线了……pull request都不理我T.T

**Comment by morethink** [comment]
我们自己改了可以用不?

**Comment by tychenjiajun** [comment]
可以吧
也可以尝试一下
```shell
git clone https://github.com/tychenjiajun/qiniu-uploader.git
cd qiniu-uploader
apm install
apm link
atom
```

**Comment by morethink** [comment]
可以上传了，厉害 @tychenjiajun

**Comment by morethink** [comment]
怎么选择图片格式和名字？ @tychenjiajun

**Comment by tychenjiajun** [comment]
@morethink 因为剪贴板的数据本身是不带图片格式的，目前便于呈现所以用了png
名字为了不冲突，使用了生成的md5值
如果你需要选择图片格式和名字功能的话，我有空再试着做吧

**Comment by morethink** [comment]
@tychenjiajun 谢谢

**Comment by Marina-Ma** [comment]
修改了还是不行诶

![image](https://user-images.githubusercontent.com/33084062/32336768-25334132-c02b-11e7-92e0-aa868eb00d92.png)

跳出来还是这个问题，这张图只能放大看了
![default](https://user-images.githubusercontent.com/33084062/32336856-69dc8136-c02b-11e7-9d0a-9ed8cb88e2ea.PNG)

**Comment by tychenjiajun** [comment]
@Marina-Ma 需要先删除原有的qiniu-uploader

**Comment by knightli** [comment]
thx @tychenjiajun   merged
