### ISSUE TITLE
上传已存在图片时异常(粘贴图片正常)

### ISSUE THREAD

**Issue by xiaozhaoosc** [knightli/qiniu-uploader#13]
.atom\packages\qiniu-uploader\lib\main.coffee:30
Hide Stack Trace
TypeError: _this.toggle is not a function
    at HTMLElement.subscriptions.add.atom.commands.add.qiniu-uploader:toggle (file:///C:/Users/zhaoxuan/.atom/packages/qiniu-uploader/lib/main.coffee:30:89)
    at CommandRegistry.handleCommandEvent (C:\Users\kenzhao\AppData\Local\atom\app-1.22.1\resources\app\src\command-registry.js:381:36)
    at Object.didConfirmSelection (C:\Users\kenzhao\AppData\Local\atom\app-1.22.1\resources\app\node_modules\command-palette\lib\command-palette-view.js:144:35)
    at SelectListView.confirmSelection (C:\Users\kenzhao\AppData\Local\atom\app-1.22.1\resources\app\node_modules\command-palette\node_modules\atom-select-list\src\select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (C:\Users\kenzhao\AppData\Local\atom\app-1.22.1\resources\app\node_modules\command-palette\node_modules\atom-select-list\src\select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (C:\Users\kenzhao\AppData\Local\atom\app-1.22.1\resources\app\src\command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\kenzhao\AppData\Local\atom\app-1.22.1\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\kenzhao\AppData\Local\atom\app-1.22.1\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\kenzhao\AppData\Local\atom\app-1.22.1\resources\app\src\window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (C:\Users\kenzhao\AppData\Local\atom\app-1.22.1\resources\app\src\window-event-handler.js:3:65)

**Comment by tychenjiajun** [comment]
已存在图片是指已在文件系统中存在呢还是已在七牛中存在呢

**Comment by xiaozhaoosc** [comment]
是指已在文件系统中存在的，从百度下载的一个图片到电脑中的；然后将这个图片上传到七牛

**Comment by tychenjiajun** [comment]
@xiaozhaoosc 暂不支持这个功能

**Comment by xiaozhaoosc** [comment]
了解，感觉这个功能也是挻重要的呢；比如做PPT，都是提前准备好的素材。

**Comment by chenghm123** [comment]
https://github.com/chenghm123/md-writer-qiniu

一步到位 解决了

**Comment by luoei** [comment]
也是无法使用，寻找的其它方法：[markdown-write-qiniu](https://github.com/xispower/md-writer-qiniu)

**Comment by chenghm123** [comment]
> 也是无法使用，寻找的其它方法：[markdown-write-qiniu](https://github.com/xispower/md-writer-qiniu)

ctrl + shift + i

快捷键不是ctrl + v

**Comment by chenghm123** [comment]
> 也是无法使用，寻找的其它方法：[markdown-write-qiniu](https://github.com/xispower/md-writer-qiniu)
这边版本也可以、、

**Comment by chenghm123** [comment]
> 也是无法使用，寻找的其它方法：[markdown-write-qiniu](https://github.com/xispower/md-writer-qiniu)

这边好像就是fork我改了改、、、、
