### ISSUE TITLE
Uncaught ReferenceError: err is not defined

### ISSUE THREAD

**Issue by liufree** [knightli/qiniu-uploader#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: "Fedora release
**Thrown From**: [qiniu-uploader](https://github.com/knightli/qiniu-uploader) package 0.0.5

### Stack Trace

Uncaught ReferenceError: err is not defined

```
At /home/liufree/.atom/packages/qiniu-uploader/lib/uploader.coffee:36

ReferenceError: err is not defined
    at /packages/qiniu-uploader/lib/uploader.coffee:36:18
    at /packages/qiniu-uploader/node_modules/qiniu/qiniu/storage/form.js:74:9
    at /packages/qiniu-uploader/node_modules/qiniu/qiniu/zone.js:77:7
    at done (/packages/qiniu-uploader/node_modules/urllib/lib/urllib.js:444:5)
    at /packages/qiniu-uploader/node_modules/urllib/lib/urllib.js:693:9
    at decodeContent (/packages/qiniu-uploader/node_modules/urllib/lib/urllib.js:517:14)
    at /packages/qiniu-uploader/node_modules/urllib/lib/urllib.js:658:7)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
  2x -0:09.8.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
bracket-colorizer 1.3.0 
clipboard-plus 0.5.1 
darcula-syntax 0.2.1 
dracula-ui 0.6.0 
GobbieGobGoo 1.0.4 
markdown-assistant 0.2.0 
markdown-img-qiniu 2.0.0 
markdown-preview-enhanced 0.15.10 
markdown-table-editor 1.1.1 
markdown-themeable-pdf 1.2.1 
markdown-writer 2.11.5 
pdf-view 0.71.0 
qiniu-uploader 0.0.5 
tool-bar 1.1.11 
tool-bar-markdown-writer 0.5.0 
trans-en-zh 0.2.5 
vim-mode-plus 1.36.0 
```

**Comment by tychenjiajun** [comment]
@liufree try rename `err` to `respErr`

pull request is welcomed
