### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by huybery** [knightli/qiniu-uploader#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.9
**System**: linux 4.7.6-1-ARCH
**Thrown From**: [qiniu-uploader](https://github.com/knightli/qiniu-uploader) package, v0.0.3
### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /home/huybery/.atom/packages/qiniu-uploader/node_modules/qiniu/node_modules/sync-request/index.js:10

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Object.<anonymous> (/home/huybery/.atom/packages/qiniu-uploader/node_modules/qiniu/node_modules/sync-request/index.js:10:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/huybery/.atom/packages/qiniu-uploader/node_modules/qiniu/qiniu/zone.js:1:94)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/huybery/.atom/packages/qiniu-uploader/node_modules/qiniu/qiniu/io.js:11:12)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/huybery/.atom/packages/qiniu-uploader/node_modules/qiniu/index.js:8:7)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/huybery/.atom/packages/qiniu-uploader/lib/uploader.coffee:1:9)
    at Object.<anonymous> (/home/huybery/.atom/packages/qiniu-uploader/lib/uploader.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/huybery/.atom/packages/qiniu-uploader/lib/main.coffee:1:12)
    at Object.<anonymous> (/home/huybery/.atom/packages/qiniu-uploader/lib/main.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:222:12)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:216:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:159:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:171:21)
    at PackageDetailView.module.exports.PackageDetailView.initialize (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:146:19)
    at PackageDetailView.View [as constructor] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at PackageDetailView.ScrollView [as constructor] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new PackageDetailView (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:38:54)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-view.js:267:22
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-view.js:272:19)
    at SettingsView.module.exports.SettingsView.showPanel (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-view.js:318:24)
    at space-pen-div.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:272:83)
    at space-pen-div.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -7:43.5.0 core:paste (atom-text-editor#markdown-img-paste.zdomain.editor.mini.is-focused)
     -7:41.5.0 core:save (atom-text-editor#markdown-img-paste.zdomain.editor.mini.is-focused)
  4x -7:37.1.0 markdown-img-paste:paste (atom-text-editor.editor.is-focused)
     -7:33.4.0 core:paste (atom-text-editor.editor.is-focused)
     -7:32 core:undo (atom-text-editor.editor.is-focused)
  7x -7:21.3.0 markdown-img-paste:paste (atom-text-editor.editor.is-focused)
     -7:15.5.0 core:backspace (atom-text-editor.editor.is-focused)
 82x -7:14.8.0 markdown-img-paste:paste (atom-text-editor.editor.is-focused)
     -5:05.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -5:02.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:41.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -4:40.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:42.7.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:42.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "editor-background"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-beautify"
    ],
    "themes": [
      "atom-material-ui",
      "flat-ui-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.12 (active)
atom-css-comb, v3.1.0 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (active)
atom-ternjs, v0.15.0 (active)
dracula-theme, v1.2.8 (inactive)
dracula-ui, v0.3.0 (inactive)
editor-background, v1.2.23 (inactive)
file-icons, v1.7.19 (active)
firewatch-syntax, v1.0.1 (inactive)
flat-ui-syntax, v0.4.0 (active)
jquery-snippets, v11.0.0 (active)
language-vue, v0.16.1 (active)
markdown-assistant, v0.2.0 (active)
pigments, v0.34.0 (active)
platformio-ide-terminal, v2.2.0 (active)
qiniu-uploader, v0.0.3 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.1 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by LouisMari1991** [comment]
我也遇到了这个问题,有人解决了麽？

**Comment by x7peeps** [comment]
@MariShunxiang @huybery  先安装markdown-assistant在安装这个。可以解决。
