### ISSUE TITLE
Enter steps to reproduce below

### ISSUE THREAD

**Issue by mxisme** [knightli/qiniu-uploader#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: [qiniu-uploader](https://github.com/knightli/qiniu-uploader) package, v0.0.3
### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At C:\Users\xy\.atom\packages\qiniu-uploader\node_modules\sync-request\index.js:10

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Object.<anonymous> (C:\Users\xy\.atom\packages\qiniu-uploader\node_modules\sync-request\index.js:10:1)
    at Module._compile (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\xy\.atom\packages\qiniu-uploader\node_modules\qiniu\qiniu\zone.js:1:94)
    at Module._compile (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\xy\.atom\packages\qiniu-uploader\node_modules\qiniu\qiniu\io.js:11:12)
    at Module._compile (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\xy\.atom\packages\qiniu-uploader\node_modules\qiniu\index.js:8:7)
    at Module._compile (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/xy/.atom/packages/qiniu-uploader/lib/uploader.coffee:1:9)
    at Object.<anonymous> (file:///C:/Users/xy/.atom/packages/qiniu-uploader/lib/uploader.coffee:1:1)
    at Module._compile (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/xy/.atom/packages/qiniu-uploader/lib/main.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/xy/.atom/packages/qiniu-uploader/lib/main.coffee:1:1)
    at Module._compile (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:721:27)
    at Package.module.exports.Package.activateConfig (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:225:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:55:14)
    at PackageCard.module.exports.PackageCard.hasSettings (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:699:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:397:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:390:12)
    at C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:643:24
    at C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-card.js:712:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:680:27)
    at C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:468:26
    at exit (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\xy\AppData\Local\atom\app-1.11.1\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```
### Commands

```
     -1:08.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:06.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ],
    "packagesWithKeymapsDisabled": [],
    "telemetryConsent": "limited"
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v1.0.2 (active)
language-markdown, v0.16.3 (active)
markdown-assistant, v0.2.0 (active)
markdown-pdf, v1.5.0 (inactive)
markdown-scroll-sync, v2.1.2 (active)
markdown-toc, v0.4.1 (inactive)
qiniu-uploader, v0.0.3 (inactive)
simplified-chinese-menu, v3.5.0 (active)
tool-bar-markdown-writer, v0.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Jason8Kang** [comment]
the same error with you ,what's worese,I  have no setting icon.

**Comment by Jason8Kang** [comment]
do you solve it now?
