### ISSUE TITLE
不太懂什么意思

### ISSUE THREAD

**Issue by ghost** [knightli/qiniu-uploader#7]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Unknown Windows Version
**Thrown From**: [qiniu-uploader](https://github.com/knightli/qiniu-uploader) package, v0.0.3

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At C:\Users\Administrator\.atom\packages\qiniu-uploader\node_modules\qiniu\node_modules\sync-request\index.js:10

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (native)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\qiniu-uploader\node_modules\qiniu\node_modules\sync-request\index.js:10:1)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\qiniu-uploader\node_modules\qiniu\qiniu\zone.js:1:94)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\qiniu-uploader\node_modules\qiniu\qiniu\io.js:11:12)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\qiniu-uploader\node_modules\qiniu\index.js:8:7)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/qiniu-uploader/lib/uploader.coffee:1:9)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/qiniu-uploader/lib/uploader.coffee:1:1)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/qiniu-uploader/lib/main.coffee:1:12)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/qiniu-uploader/lib/main.coffee:1:1)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateConfig (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:222:12)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:220:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:163:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:175:21)
    at C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:306:17
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:672:27)
    at C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:460:26
    at exit (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.7.3\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -2:18.8.0 command-palette:toggle (div.panels-item)
     -2:10.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:58.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:54.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:05.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
javascript-snippets, v1.2.1
markdown-assistant, v0.2.0
php-integrator-autocomplete-plus, v0.8.1

# Dev
No dev packages
```

**Comment by jingchen2222** [comment]
I think the issue just the same with issue 6.
https://github.com/knightli/qiniu-uploader/issues/6

You will find some suggestions from it.
